### ISSUE TITLE
Login takes a long time

### ISSUE THREAD

**Issue by humble-GOAT** [Pleb5/satshoot#30]
I logged in as a new user - freelancer. Page took long time to load after signing in, probably this is due to web of trust calculation. 

Maybe this should be a background process?

**Comment by Pleb5** [comment]
First "cold-start" login takes several seconds, maybe even 6-7secs(depending on network) but then caching should make it much faster on consecutive logins.

 Would be interested to know exactly how long it took for you and what were the circumstances.

That said, because the app takes wot seriously: the user is not allowed to see global before wot is loaded.  Otherwise he would see things disappear which would be a problematic experience.

**Comment by humble-GOAT** [comment]
I measured the process, and it took approximately 10 seconds to complete.


Operating System: Linux Mint
Web Browser: Chrome
Extension: Nos2x
